--- #YAML:1.0
name:               File-Temp-Trace
version:            0.02
abstract:           Trace the creation of temporary files
author:
    - Robert Rothenberg <rrwo@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Attribute::Handlers:  0
    Carp:                 0
    File::Path:           0
    File::Spec:           0
    File::Temp:           0
    IO::File:             0
    overload:             0
    Scalar::Util:         0
    self:                 0
    Test::More:           0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
